### ISSUE TITLE
Work Unavailability Boundaries

### ISSUE THREAD

**Issue by ksanusi** [Apexal/late#111]
If a person says that they can't work from, for example, 2AM - 10 AM, the website is not able to show their available time for 10AM-2AM.

**Comment by Apexal** [comment]
Yes, I'm not exactly sure how we'd get around this. Since in the current setup 2AM is technically before 10AM, we'd have to have the ability to set 2AM as the next date.

**Comment by Apexal** [comment]
This is going to be trickier than planned due to the auto-allocating work.

**Comment by Apexal** [comment]
Fixed by changing minTime and maxTime to use businessHours such as `27:00` for 3 am
