### ISSUE TITLE
Improve UX/UI

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#118]

**Comment by AbigailMedina** [comment]
work on smallUIChanges branch for this kind of work
First things to work on
-label priority bar
-change favicon
-...

**Comment by IncognitoCactus** [comment]
I've found a couple of really small things we can fix:
**Setup:**
- Text message input doesn't like 10-digit numbers with no dashes
- "Your Profile" progress bar is clickable but the cursor doesn't reflect that
- Integrations progress icon remains incomplete even if we've gone through it
  - maybe an option to say "no thanks" to integration?

**Assignments:**
- Capitalization on courses are in titlecase- bad for courses like RCOS (shown Rcos) or Calculus II (shown Calculus Ii)
- "Past Assignments" start/end/Last Week/Goto week have inconsistent spacing

**Comment by Apexal** [comment]
@IncognitoCactus unfortunately the wacky course names come straight from the YACS API so we cannot really fix them without a lot of hardcoding.

**Comment by Apexal** [comment]
I fixed the PastAssignments button spacing to be centered.

**Comment by Apexal** [comment]
SMS verification now allows dashes or no dashes.
