### ISSUE TITLE
YACS API Integration

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#12]
Looks like the YACS API is going public or something like that.

## We can use this for users to track what courses they are in

**Comment by t80088** [comment]
Could be useful to have a button when they're setting up that offers to put their classes on google calendar, shouldn't really be any more work than normal as we're already using both the YACS API and the Google Calendar API.

If we wanted to go further than that we could also ask them how they want it to show up on their schedule (actual address of the building vs building name + room number, round to hour or not (a class ending at 4:50 would show as ending at 5), etc.

**Comment by Apexal** [comment]
I will speak to Ada Young about this soon.
