### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#123]
Instead of just leaving text comments on assignments, that tab should show the progression the user goes through working on the assignment.

It will be a sort of timeline keeping track of when the user works on an assignment, with optional status updates from the user.

**Comment by Apexal** [comment]
Instead of replacing comments, this can just be the tab in between "Work Schedule" and "Comments" that shows a timeline of when the assignment was worked on, when it was edited, etc.

**Comment by Apexal** [comment]
This is kinda tricky seeing as work blocks are going to be so dynamic. I'm not sure if this is worthwhile. I'm going to mark this as wontfix for now.

**Comment by AbigailMedina** [comment]
I would really like to see this issue worked on. This can be simple if we calculate how much time is in passed work blocks/time scheduled and every time a work block passes, the completion bar will adjust

**Comment by Apexal** [comment]
@AbigailMedina
I envisioned a sort of timeline showing the history of the assignment/exam and work blocks scheduled for it.

It sounds like you are envisioning more of a literal progress bar based on the total work block time and the passed work block time. Is that correct?
