### ISSUE TITLE
CAS Login loop

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#124]
Some of us have reported getting stuck in a CAS loop where clicking login on the CAS page just redirects to the CAS page and does not allow you to login...

**Comment by Colton-Zecca** [comment]
Tested issue and appears to be fixed.

**Comment by Shadowsoftime99** [comment]
CAS Loop is appearing again, this time occasional and leaving and re-entering the login page fixes it. Notable is that the Heroku server does _not_ receive any requests until a successful login attempt goes through

**Comment by Apexal** [comment]
This still happens and I have no idea why.

**Comment by Apexal** [comment]
STILL happens and I can't determine the cause.

**Comment by robere2** [comment]
I'm not convinced this is an issue with LATE. If you look at the network logs of a normal signin, you will see this request:
`POST https://cas-auth.rpi.edu/cas/login?service=https%3A%2F%2Fwww.late.work%2Fauth%2Flogin&renew=false`
The response is a 302 FOUND with the header: `Location: https://www.late.work/auth/login?ticket=REDACTED`

If you look at the network logs of one with a redirect loop however, you will see the same request: `POST https://cas-auth.rpi.edu/cas/login?service=https%3A%2F%2Fwww.late.work%2Fauth%2Flogin&renew=false`
except the response is a 200 OK with no `Location` header. This happens every time. 

Everything about the browser's request (i.e. headers) are what you would expect. They are near identical in both cases, and it is only the server response that differs. Most importantly, the response body is not empty, but instead the same response as the initial `GET` request. It is almost as if it is responding with the "incorrect password" message, except without the actual bubble which says incorrect password.

It might be worth attempting to [contact DotCIO](https://info.rpi.edu/people/division-chief-information-officer) to see if we can get any more information.

**Comment by Apexal** [comment]
I switched to using Passport, and while it has its own issues because of Koa instead of Express... I have not run into the issue yet and it is better organized code
