### ISSUE TITLE
Improve About page

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#126]
Currently the About page only has the names of the team members. It should also have sections about **LATE** as a whole and an overall idea of current features *and planned features.*

**Comment by Apexal** [comment]
I should give a short description of the vision of the project and its roots in OnTrac.

**Comment by AbigailMedina** [comment]
move team names to rebooted homepage since aboutPage is dead

**Comment by AbigailMedina** [comment]
styling issues on small screen(phone)

**Comment by Apexal** [comment]
@AbigailMedina The mobile styling issues should be worked on today.

**Comment by AbigailMedina** [comment]
> @AbigailMedina The mobile styling issues should be worked on today.

is this done? it looks like it is. Pls close it or reply with update

**Comment by Apexal** [comment]
There still is technically an About page that is not linked to anywhere noticeable. I'll figure out what to do about that today.

**Comment by Apexal** [comment]
I'm just procrastinating writing the about page cause I don't know how much info to put or how to word everything. I will get to this soon.

**Comment by IncognitoCactus** [comment]
I updated the About page to match the rest of the site's theme and wrote a sales pitch of sorts for the description. Feel free to update it if needed but for now I'll close this issue.
