### ISSUE TITLE
Exam System

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#131]
So far LATE can handle assignments but not exams.

**Key Features**
- [x] Add exams as separate from assignments
- [x] Exams have durations and show up on the calendar
- [x] Exams route similar to assignments (upcoming, past, calendar?)
- [x] Dashboard shows exams as well
- [x] Exams don't have a completed status, just whether or not the `date` has passed
- [x] Exams will have more complicated descriptions (a study guide format with checkable items)
- [x] Sidebar has upcoming exams
- [x] Exam comments
- [x] Exam reminder notifications
- [x] Exam comments #237

**Comment by Apexal** [comment]
Something should be done to make sure exams don't creep up unnoticed. There should be the option for customizable reminder notifications (email probably best) to remind users of scheduled exams, as well as notifications somewhere (the Dashboard)

**Comment by Apexal** [comment]
Bumping because a PSoft exam crept up on me unnoticed even though I had it in LATE since the first semester. :( I'm blind

**Comment by robere2** [comment]
This might be dependent on a core notification system first (is there an issue for this? What's the status?).

**Comment by Apexal** [comment]
Thank you for reminding me! I was about to open an issue "Assessment Notifications" covering exactly that but my delivery of dumplings arrived and distracted me B) I'll open it now with info
