### ISSUE TITLE
LVP

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#14]
## LVP Progress
- [x] Input weekly free time
- [x] Add assignments with due date and time estimate
- [x] Allow editing/deleting assignments
- [x] Toggle completion of assignments
- [x] View list of assignments chronologically (similar to Google Tasks)

**Note:** This list makes LATE a slightly customized to-do list and not much else. I personally believe this is enough for a LVP because it would be useful on its own before we even begin to implement the auto-scheduling feature. *You may not agree that this list is enough for a LVP. Please comment your opinion!*

**Comment by Shadowsoftime99** [comment]
User should be able to:
-Enter/import their class times/schedule (manually, later integrations possibly with Google Calendar, YACS, etc.)
-Enter their HW assignments, due dates, and estimated length of each
-View a schedule that is their schedule, overlaid with auto-placed time slots for their assignments

**Comment by IncognitoCactus** [comment]
Later on we should provide:
- Ability to specify "prefer/avoid" times for homework scheduling
- An (optional?) sign-in system for saving user data
  - Saving classes and allowing the user to add assignments for the class (from a drop-down menu or perhaps a tag system.)

**Comment by AbigailMedina** [comment]
Set of Views:
Main: 
- add assignment,
- view schedule
- add existing scheduled "no work blocks"
Planner:
- list of assignments w/ check done, cross off
