### ISSUE TITLE
Unable to Click Save & Continue When Setting up Account

### ISSUE THREAD

**Issue by Colton-Zecca** [Apexal/late#156]
Unable to click Save & Continue when setting up account if you don't put in any 'Busy' blocks in yourself (https://rpi-late.herokuapp.com/profile/unavailability). The button to save is greyed out and you can't click it until you add at least one Busy block.

**Comment by Apexal** [comment]
This was meant as a feature but understandably should be fixed.

Glancing over the code, I think changing the Vue instance data property `saved` to `false` at https://github.com/Apexal/late/blob/2251b9d5439e7a704baab832826ecf5d4f3d95a4/src/views/profile/ProfileSetupUnavailability.vue#L105 should fix it, but I'm not positive.
