### ISSUE TITLE
No Backend Date Validation

### ISSUE THREAD

**Issue by Colton-Zecca** [Apexal/late#158]
When adding a new assignment, you can change the HTML property for the minimum date using dev tools. Potential to cause backend conflict and other errors. Possibly allow users to add assignments in the past as a method of keeping track of previous assignments.

**Comment by Apexal** [comment]
Good catch. There are multiple places where just to get it working quickly I only implemented front-end validating. These will all have to be identified and added to the backend as well.

Adding past assignments to the past is an interesting idea, but how do we handle completion? We just create it as a completed assignment? We also wouldn't be able to track work block data on created past assignments.
