### ISSUE TITLE
Adding an assignment should show it once you close out of the add assignment screen

### ISSUE THREAD

**Issue by Colton-Zecca** [Apexal/late#159]
Either force refresh the page or manually add it to the page for a more seamless experience.

**Comment by Apexal** [comment]
Can you elaborate? It should be immediately displayed as it is added to the internal list of upcoming assignments. It would show on the screen if you are viewing the Upcoming Assignments page, and it should show in the sidebar tab for Pressing Assignments (unless there already are more recent assignments showing).
