### ISSUE TITLE
Account setup notification dismissability

### ISSUE THREAD

**Issue by IncognitoCactus** [Apexal/late#167]
In addition to addressing the issue brought up by @Colton-Zecca [regarding account setup completion](https://github.com/Apexal/late/issues/157), we should add functionality to dismiss notifications such as the one appearing above your calendar reading "NOTICE: You will not be able to use LATE until you have set up your account".

**Comment by Apexal** [comment]
If #157 gets fixed, this shouldn't be an issue because you can go through the setup steps without entering info and it will count as setup.
