### ISSUE TITLE
Allow naming of "busy" blocks on way to Club integration

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#174]
As the busy blocks are background events, manually change it to allow text on background events OR dont make it a background event and manually set the opacity styling

**Comment by Apexal** [comment]
This has become an annoyance to my use recently; I finally see the need for this. We will start it today.

**Comment by Apexal** [comment]
As the scope of LATE grows, I guess it is inevitable that we start encroaching on Google Calendar. I will implement busy blocks as named events.
