### ISSUE TITLE
Dashboard Schedule Cuts off Courses earlier than Earliest Time Preference

### ISSUE THREAD

**Issue by henryjeff** [Apexal/late#177]
If a user chooses their earliest time preference to be after a course that is in the morning it will be cut off the schedule. This is a quick fix, but making sure the dashboard doesn't visually cut off any courses is rather important.

**Comment by Apexal** [comment]
Good catch, I didn't think of the obvious scenario where a user would set their earliest time preference later than some of their class start times.

**Comment by Apexal** [comment]
This is fixed now with commit d2285e2adf83eb7b090de8b20a453954dc81c582 indirectly
