### ISSUE TITLE
Allow deletion for assignments added in the past

### ISSUE THREAD

**Issue by henryjeff** [Apexal/late#180]
If you create an assignment in the past, you are locked from editing it and that in turn prevents you from removing it if you wanted to.

**Comment by Apexal** [comment]
We can simply replace the edit button (which is hidden on past assessments) with a direct delete button.

**Comment by SamiFawcett** [comment]
- put remove button as a column on the assigments table
- put remove in place of edit on the past assignment page.

**Comment by Apexal** [comment]
I would change the class of the remove button to be `is-warning` because for a past event that was completed (most likely), it looks like this:

![screenshot](https://snag.gy/Ewi067.jpg)

**Comment by SamiFawcett** [comment]
Will do!
