### ISSUE TITLE
Edit Assessments in Place

### ISSUE THREAD

**Issue by henryjeff** [Apexal/late#181]
Update Assignment Edit, Exam Add and Exam Edit modals to use the new modal components.
- [x] Assignment Edit
- [x] Exam Add
- [x] Exam Edit

**Comment by Apexal** [comment]
@henryjeff 
I refactored lots of the AssignmentAdd modal, so the ExamAddModal can just copy most of it. Some few changes will have to be made to one or more of the components (exams shouldn't have the recurring option)

**Comment by Apexal** [comment]
We are moving away from edit modals in order to allow editing in place for all assessment data. Once this is done we will be able to delete the edit modals.
