### ISSUE TITLE
Dev Server does not allow access to pages that dont require login

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#189]
I cannot access /homepage when using the dev server. It instead redirects to 404, Page does not exist.

**Comment by Apexal** [comment]
A current work around is building locally `$ npm run build-dev` and going to `localhost:3000` instead of using the hot reloading dev server.

**Comment by AbigailMedina** [comment]
> A current work around is building locally `$ npm run build-dev` and going to `localhost:3000` instead of using the hot reloading dev server.

actually npm run build-dev then npm run dev. Upon each save, will have to ^C and npm run build-dev then npm run dev again.

**Comment by Apexal** [comment]
I could perhaps make it so if you cancel the prompt that asks for the rcs_id of the user to login to, it lets you just go to the homepage.

**Comment by Apexal** [comment]
Now if you don't enter a username, it lets you browse the site as not logged in!
