### ISSUE TITLE
Sidebar is a little too wide on mobile

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#196]
One my OnePlus 6 on Chrome, the sidebar appears to jut slightly out to the right, causing an empty line of space on the right:

<img src="https://dl2.pushbulletusercontent.com/bYxIloaO1s2TqGmiqicWblsTKRicfx1G/Screenshot_20190129-005737.jpg" width="200">

**Comment by henryjeff** [comment]
Just tested on a Pixel 2 XL and an iPhone 8 with the same results
