### ISSUE TITLE
Assessment descriptions word wrap

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#197]
Assessment descriptions with long links (very long words) jut entirely out of the blockquote and off the page ruining the container:

<img src="https://dl2.pushbulletusercontent.com/Heab2rtfw2yJKk4qUgpgGr6jb5OubnVu/Screenshot_20190129-010200.jpg" width="200">

I believe this is a problem with CSS word wrap not being set properly.

**Comment by henryjeff** [comment]
As a side note, this is also the case with exam descriptions.

**Comment by Apexal** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by arachiele** [comment]
this also happens on desktop version
