### ISSUE TITLE
Waitlist for big number of interested people that we don't want (yet)...

### ISSUE THREAD

**Issue by GBLiH** [Apexal/late#216]
Hey there just had an idea for the "issue" of the post on Reddit that resulted in an increase in the interest for LATE. Frank isn't interested in having the public know of LATE quite yet since we wanna make it the best it can be and so to not lose that interest we can make an e-mail waitlist for those interested. 
Another idea is for the "inactive" testers in LATE that would be sending refreshers to them, via e-mail or SMS.

**Comment by Apexal** [comment]
Great idea! It has now been implemented.
