### ISSUE TITLE
Schedule new work blocks directly from dashboard

### ISSUE THREAD

**Issue by arachiele** [Apexal/late#221]
Make it easier to schedule work time. Feature idea: when the user clicks an open time slot in the calendar, a pop up screen allows you to check which assignment you want to work on at the time, and since LATE already knows your assignments you can just pick from the list. Or as an alternative, the user could drag assignments from the assignment bar and “drop” work times into the schedule directly from dashboard.  Personally I like looking at a full calendar and scheduling based off when I am doing other things, so this could help with user interface.

**Comment by Apexal** [comment]
This is almost done!
