### ISSUE TITLE
Added Assignments in Chronological Order

### ISSUE THREAD

**Issue by lopeza8** [Apexal/late#231]
As I was adding a bunch of assignments all a once, they were appearing in the order that I was adding them in (see picture). They reorganized once I refreshed the page though. They should be organized as soon as they're added. 

![latepic](https://user-images.githubusercontent.com/44064481/52508019-35a1f600-2bc1-11e9-90cb-9e359f9f0826.png)

**Comment by Apexal** [comment]
My commit does not work...?

**Comment by Apexal** [comment]
Finally fixed. Adding/updating assignments now require dispatching a Vuex action that adds/updates and then calls a sort mutation.
