### ISSUE TITLE
Allow editing of past assignments

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#244]
Use case:  I had a hw that was due last week but the due date got pushed back to this week. Since the deadline already passed, I can't currently edit its due date and schedule work time for it this week. I would like to be able to edit old assignments fields(not allowing adding of work blocks past the due date though, they would have to move the due date to a later time.)

**Comment by Apexal** [comment]
These restrictions were intentional (I didn't think of this case) so they will be easy to undo.

**Comment by AbigailMedina** [comment]
on branch editOverdue
