### ISSUE TITLE
Inconsistent style of page headers

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#246]
@IncognitoCactus pointed out that the Dashboard header with the tabs:
![screenshot](https://snag.gy/6CbLUv.jpg)
is not consistent with the Assignments/Exams page headers:
![screenshot](https://snag.gy/OZFwNK.jpg)

These should match. I'm not sure which of the two styles would look better, so both should be experimented with.

**Comment by IncognitoCactus** [comment]
On it, gonna go with the dashboard styling for all the pages, but keep the cool "outline" button look for other elements.
