### ISSUE TITLE
"Close" button on modals

### ISSUE THREAD

**Issue by IncognitoCactus** [Apexal/late#257]
This should be a quick fix. Right now the only option to close out of a modal (like "Add Assignment" or "Add Exam") is to click outside of the box. However, it would be more accessible to add an x button which also closes the modal.

Something like this:
![screenshot from 2019-02-25 16-33-53](https://user-images.githubusercontent.com/12072877/53370230-33f36480-391b-11e9-8af7-0dc0ee4d1230.png)

**Comment by AbigailMedina** [comment]
@IncognitoCactus there is already a button: "cancel" which closes the modal. I think it would be redundant and confusing to have a cancel and a close button since they would do the same thing. Respond or close this issue.
