### ISSUE TITLE
Edit Assignment Bug

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#273]
**Describe the bug**
Editing an assignments due time is broken

**To Reproduce** 
-go to an assignment page
-click edit details button (yellow)
-edit the due time
-save
-notice the due time is reset to 12am until refresh of page

**Comment by AbigailMedina** [comment]
Files involved: AssignmentsOverview.vue renders AssignmentsModalEdit which has a @edit-assignment="updatedAssignment" to get the new assignment after edit-assignment is emmitted. AssignmentsOverview.vue also renders AssignmentOverviewStats which has prop "assignment". So when the assignment is edited in the modal, the data in AssignmentsOverview should be updated and the new version should be sent to Stats which should rerender on its prop change. However, this isnt working. Still not sure why

**Comment by Apexal** [comment]
I actually just went to change the due date of an assignment and it refused, with the error `Cannot read property 'start' of undefined`...

**Comment by Apexal** [comment]
The above issue I noted turned out to be a totally separate bug I accidentally caused.

**Comment by Apexal** [comment]
It actually seems like this is a server-side bug. When the assignment is updated on the backend its supposed to return the edited assignment. It appears that the returned assignment always has no time on the `dueDate` property, hence `12 am`

**Comment by Apexal** [comment]
Ohhhhhhhhhhhhhhhhhhhh wait.

The client is not sending the time as part of `dueDate` to the server in the `PATCH /assignments/:assignmentID` call. This is because time and due date are separated on the client when adding/editing assessments.
