### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by IncognitoCactus** [Apexal/late#279]
We should probably begin shifting our coloring styles to work off of variables rather than hardcoded colors, in preparation for potentially theming the site.
Ideally, we'd be able to swap to another sass file containing all the coloring information and have that reflected across the site.
Bulma has support for variable-based styling, but we'd also need to define our own sass variables to fill in the gaps.

Something like this:

![Screenshot from 2019-03-19 16-44-38](https://user-images.githubusercontent.com/12072877/54640513-5f72f600-4a66-11e9-866b-4209ada09111.png)

**Comment by IncognitoCactus** [comment]
Small update: Vue does support hot swapping css files to some extent, and the site is all ready for theming support. Just gotta figure it out. It's low priority for now.

**Comment by Apexal** [comment]
Out of LATE's scope.
