### ISSUE TITLE
Bug on upcoming assignments scheduling time vs estimate time

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#280]
**Describe the bug**
[Describe the problem that occurred as best as you can here]

**To Reproduce** *optional*
*Example:*
1. Have an assignment with some time estimated for scheduling
2. Schedule more than estimated time for the assignment
3. Look at upcoming assignments to see it still says you need to schedule more time

**Expected behavior**
It should have a success icon and the on hover title of the icon should be something implying successfull scheduling

**Screenshots** *optional*
![Screen Shot 2019-03-19 at 5 47 53 PM](https://user-images.githubusercontent.com/9837236/54644363-78cc7000-4a6f-11e9-884f-470b2b386070.png)

**Comment by Apexal** [comment]
I checked out this quickly without being able to test the code, but I think the opacity is just flipped, i.e. it returns opacity values thinking 0 was fully visible and 1 was invisible but it is the opposite.

**Comment by Apexal** [comment]
Fixed!
