### ISSUE TITLE
Cant log past work due to disabled arrow buttons

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#286]
**Describe the bug**
Arrow buttons are disabled on AssessmentOverviewWorkSchedule page for time before the assignment was created

**To Reproduce** *optional*
1. Create an assignment or use an assignment that was created recently
2. Go to the overview page for the assignment
3. Try to go to a week that is before the assignment's creation date
4. See image for buttons I'm talking about

**Expected behavior**
The user should be able to travel back in time in case the assignment was made after having done some work on it and the user wants to log when work was done on it for their own reference. Don't disable the back button until the beginning of the semester, disabling of the future button makes sense as it is(after due date it is disabled)

**Screenshots** *optional*
![Screen Shot 2019-03-23 at 7 54 23 PM](https://user-images.githubusercontent.com/9837236/54873121-59528180-4da6-11e9-93a0-bd3dd28ae00b.png)

**Comment by Apexal** [comment]
This can be worked on today, as it's a very small change.
