### ISSUE TITLE
Merge AssignmentsCalendar and ExamsCalendar

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#290]
**Is your feature request related to a problem? Please describe.**
Currently the two separate assessment calendars are not too useful when separated.

**Describe the solution you'd like**
There should be one AssessmentCalendar that is linked under both Assignments and Exams.

**Additional context** *optional*
The calendar should have options for filtering out assignments, exams, courses, etc.

**Comment by kvverti** [comment]
Pinned to #292
