### ISSUE TITLE
Logic needs work on coursework merge—exam completion

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#301]
**Describe the bug**
Exams should be marked complete automatically when the "due date" passes or not have a completion status at all

**To Reproduce** *optional*
1. Make a fake exam in the past
2. See the fake exam in the passed coursework page is marked as incomplete

**Expected behavior**
[Write what you expected to happen here.]

**Screenshots** *optional*
![Screen Shot 2019-04-06 at 5 15 55 PM](https://user-images.githubusercontent.com/9837236/55675411-19a09500-5890-11e9-8797-73c7bf6f70fa.png)
![Screen Shot 2019-04-06 at 5 14 52 PM](https://user-images.githubusercontent.com/9837236/55675413-1efddf80-5890-11e9-9f67-f58224a9b21f.png)

**Comment by Apexal** [comment]
That appears to be an assignment named "Exam 2" though, exams should be added as actual exams. These do not have completion status.

**Comment by AbigailMedina** [comment]
lol must be old whoops, will close
