### ISSUE TITLE
Record developer setup video

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#323]
Being a Node + Vue SPA setup with Vuex and webpack and all other sorts of goodies, LATE can be a pain to setup a development environment for. I will record a straightforward video going through the recommended setup covering everything from where to install Node and what versions to what editor to use and how to configure it properly for LATE.

**Comment by IncognitoCactus** [comment]
https://youtu.be/tuVYauSZFko
let me know if I missed anything.
