### ISSUE TITLE
Deleting Work Blocks from Dashboard

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#327]
From the assignment, you can click on a work block to delete it. But, from the dashboard, when you click on a work block, it brings you to the assignment. Therefore, when you're trying to schedule or delete work blocks for different assignments on the dashboard, it becomes tedious, since you have to jump from assignment to assignment to dashboard if you need to delete something.

There are a few possible solutions: 
1) when you click on the work block while on the dashboard, there is a pop-up asking whether you would like to visit an assignment or delete an assignment block. This makes the most sense and would probably be the easiest, since there is already a popup checking to see if you are sure you want to delete it.
2) add a little "x" on the top right corner of each work block on the calendar. This would now be the way to delete the work block in both the dashboard and on the assignment. I am preferential to this way, since it is user friendly and user intuitive. The current system of clicking on a work block to delete it is not common in any other calendar system, while an "x" in the upper right corner is a very clear indication of "delete". This would be a little more work if I had to guess, since it is different from the current system.

**Comment by Apexal** [comment]
Both options 1 and 2 are very possible. Option 2 would probably be nicer as its fewer clicks to do what you want to do. I will experiment with both of these options soon. Great suggestion.

**Comment by Apexal** [comment]
Option 2 is done!
