### ISSUE TITLE
Google Calendar should be in Integrations

### ISSUE THREAD

**Issue by IncognitoCactus** [Apexal/late#333]
Google Calendar is currently a separate tab of setup:
![image](https://user-images.githubusercontent.com/12072877/58129570-03ecf200-7be8-11e9-9cf3-965c79b23e45.png)

This should be in our integrations (or "notifications") tab, like so:
![image](https://user-images.githubusercontent.com/12072877/58129638-2d0d8280-7be8-11e9-9176-ae994d26d6de.png)

**Comment by Apexal** [comment]
Perhaps 'Notifications' should be renamed to 'Integrations', and then moving GCal to that would work

**Comment by Apexal** [comment]
I plan to flesh out Google integration more so this will remain its own tab.
