### ISSUE TITLE
Saving Notification Preferences doesn't work

### ISSUE THREAD

**Issue by kevinb5617** [Apexal/late#338]
After clicking button to save notification preferences, nothing happens.

**Comment by Apexal** [comment]
I foolishly reworked all the buttons on the site a few days ago and in doing so disconnected their click handlers so now they don't do anything! This and the SMS bug you noticed are caused by that. Great catch, I'll fix it ASAP and I'll look for any other broken buttons.

**Comment by kevinb5617** [comment]
Oh cool. I’m a great bug finder lolol. I guess that’s good that it’s the same bug.   
  

  
  

  
  
>
