### ISSUE TITLE
New Assignment Route

### ISSUE THREAD

**Issue by kvverti** [Apexal/late#34]
`/assignments/new`
GET - returns a page with a form to create a new `assignment`.
POST - sends form data and creates a new `assignment`.
Requires user to be logged in.

**Comment by Apexal** [comment]
Route is now protected behind CAS; assignments can now be associated with the logged in student

Only things missing now are:

- [ ] validation
- [ ] flash messages

**Comment by kvverti** [comment]
Closing since relevant request is merged.
