### ISSUE TITLE
Problem with summer arch course assignments

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#341]
Three issues: I can schedule work time and assignments, but I can no longer view any assignments. There are also issues with updating my information: my courses are being displayed, but in the information section, the courses section is shown as incomplete. LATE also begins every log in and some refreshes by informing me that I am on break, and cannot use it, and prompting me to edit my semesters.

Issue 1: Cannot view assignments
Path: Coursework --> Upcoming. Click on any assignment. 
Behavior: the page very briefly shows a grey version of the assignment, and then goes back to the upcoming page. It displays an error message at the top of the page of "Failed to get exam."

Issue 2: Course Information Bug
Path: Caitlin Bennett '22 --> Edit Account --> Course Schedule
Behavior: the Course Schedule has a grey x instead of a blue check. When in the Course Schedule tab, and on the dashboard, the courses are listed. 

Issue 3: Startup Change in Semester
Path: Dashboard
Behavior: Error message (I don't remember exactly what it says) prompting me to change the semesters I am here. The dashboard is still available with my classes showing.
Path: Caitlin Bennett '22 --> Edit Account --> School Terms
Behavior: After changing the semester, the message goes away. I have done this multiple times. After logging in again or refreshing the page, I have to do this again.

**Comment by cbnt7437** [comment]
Update: Zach was trying his best but simply cannot spell.

**Comment by Apexal** [comment]
I will investigate issue 3.
