### ISSUE TITLE
Contributor List

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#342]
It's important that every single person who's ever contributed to LATE be recognized! I will compile a list of all students (collaborators or testers) that have either contributed to the code or contributed ideas or found bugs!

This will go on the About page.

**Comment by IncognitoCactus** [comment]
Looks like the list we have in the About page covers all the developers- all we need are the testers! I'll update the page to support more names and have two separate lists for developers and testers.

**Comment by Apexal** [comment]
We can also use Bulma's tags to signify status of developer or tester
