### ISSUE TITLE
Group Work for Multiple LATE Users

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#343]
As a student currently in IED, a lot of my work blocks are done with my group members, including one group member who is also beta testing for LATE. We have to meet in person to schedule our time together, to make sure everyone is available. What if LATE could schedule group work?

Users could designate a specific assignment as a group assignment, and enter other users' emails. The assignment would then be shared with these other users and would show up on their assignment list. Any work blocks would show up on all users' dashboards. If the scheduled work block conflicts with any individuals' class or another work block, the work block would be highlighted and the user would be prompted to change it.

Since Gabe and I have classes together, we can easily test this feature.

**Comment by Apexal** [comment]
I LOVE THIS IDEA

I will work on it ASAP and have it ready for Monday.

**Comment by Apexal** [comment]
Even better, LATE can show you what time work for everyone!!!

**Comment by Apexal** [comment]
I've now added private work blocks for shared assignments so that students who share an assignment don't have to share every single work block. Non-shared work blocks will be invisible to other group members.

**Comment by Apexal** [comment]
I have just made unbelievable progress on this! Collaborators can now edit assignments and it will update for any other online collaborators in real time!!!

**Comment by Apexal** [comment]
Socket.io makes this so fun to develop. We can go so much further and implement other collaborative tools like a whiteboard or similar. Imagine just a collaborative whiteboard. That'd be like useless but so fun to make and use.

**Comment by robere2** [comment]
I think it might be important to come to a conclusion with issue #412 before progressing on this too much.

**Comment by Apexal** [comment]
Out of LATE's scope.
