### ISSUE TITLE
Allow different availability for different classes

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#344]
I don't like working on Introduction to Engineering Design past 9pm, because it requires me to be outside of my dorm and in a group setting. However, I will work on circuits past 9pm, because  I can do it at home. There are also some weeks where I want to study earlier/later than average, or I have a certain work schedule.

Availability should be adjustable by the week and by the class. I think the easiest way to do this is making availability like a work block: people can put their general availability (ex: no work from 1am to 9am) by class, and then from there, if there is an event of some sort, they can easily add unavailable spaces.

**Comment by Apexal** [comment]
Out of LATE's scope.
