### ISSUE TITLE
Automate setup process as much as possible with SIS

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#358]
The setup process should be as easy as possible. If we ask the user for their RIN and PIN immediately, we can use SIS to fill out much of the setup process:
- profile info
  - name
  - graduation year
  - major
- what terms they are on campus for
- course schedule (for current and all previous terms)
- possibly phone number (RPI alert)

**Comment by cbnt7437** [comment]
Also, SIS doesn't update if you change the classes taken or something. So, if users drop or add a class, they have to re-enter their information. Automatic updates would be nice. This is a minor detail, and would require keeping their SIS login, but I assume it would be similar to how the google calendar integration works.

**Comment by Apexal** [comment]
That would be a wonderful idea but unfortunately it would mean storing SIS RINs and passwords in our database which we could of course do but **should not be done** as it's hard to get security right when storing passwords and I don't want RPI complaining about that :(

**Comment by Apexal** [comment]
I just thought of a possible compromise: we can track the last time a student updated their info through SIS and then prompt them to re-enter their SIS credentials to update after a set amount of time has passed.

i.e. When a user logs in, check if the last time they connected to SIS was over 2 months ago. If it was, display a modal making it easy to quick type in their credentials again and reupdate from SIS.
