### ISSUE TITLE
Workload Calculator

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#359]
Given a week's courseload (assignments and exams) as well as their relative weights (priorities, timeEstimates, etc.), determine whether a week would be:
- light
- medium
- heavy

**Comment by Apexal** [comment]
What do you think of this idea? @cbnt7437 Displaying it on the Dashboard Overview page?

**Comment by cbnt7437** [comment]
Yes! That's a really great way to do a week in review (and remind us not to procrastinate on monday!)
What also might be a good feature is referencing the "2 hr of work per hour in class" rule, and creating a reminder system that prompts the user to schedule time for a break or to brush up. 
For instance, if you're in class for 6 hours of CS1 a week, and you're doing no work on CS1 that week, LATE could prompt the user to schedule a a 20-30 minute review session to keep them on track with their studies. 
Alternatively, if you have 25 hours of work (far more than the 12 hours suggested) that week, LATE could prompt the user to schedule time for a fun break in their schedule.

**Comment by Apexal** [comment]
Fantastic ideas @cbnt7437 Referencing and implementing official RPI suggestions not only will (theoretically) actually help students with reasonable guidelines but will also allow LATE to be advertised and marketed really well!

**Comment by Apexal** [comment]
Currently this does a really simple calculation where a exam counts for like 5 assignments or something. This should be revisited and revised if necessary to take priority and other things into account.
