### ISSUE TITLE
LATE cannot save my personal information

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#360]
When I tried to add a major/graduation year to my personal information, an error message came up stating that late could not save my personal information.

Steps to reproduce:
1) Click on "Edit account"
2) Click on "Manual Setup"
3) Attempt to enter information
4) Fail
![image](https://user-images.githubusercontent.com/50156900/60910034-b71fb200-a24d-11e9-9b2f-619625fad5a6.png)

(Dell XPS running on Windows 10)

**Comment by Apexal** [comment]
What do you mean by fail? Does it show the red error banner with a message?

**Comment by Apexal** [comment]
Great catch! This should be fixed. You might have to force refresh the page to have it actually update.
