### ISSUE TITLE
User Custom Courses

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#362]
I am TAing for the engineering processes class next semester, and I am also doing an undergraduate research project. Both of these things don't show up as a scheduled class on SIS, but will function as classes. 

I think a good solution for this would be to allow users to create their own class if the SIS schedule doesn't fulfill all of their classes. 

LATE could prompt the user for a class name, any regular hours of class time and what type they are (for URP, this would be something like adviser meetings, while for a TA, it would be open-shop, lecture, office hours), whether they are an instructor or a student, where the classes take place (if applicable). Then, it would create a class for the user. They could make assignments and schedule time to work on their projects, helping them have a more complete view of their schedule.

**Comment by Apexal** [comment]
This was originally planned long ago but was scrapped when we switched to grabbing courses directly from SIS. I will figure out how to add this without messing up the current SIS-only system as its an important feature to have.

**Comment by Apexal** [comment]
Out of LATE's scope.
