### ISSUE TITLE
Easter Eggs

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#363]
We are making our own website! We cannot let it be boring. There should be a handful of easter eggs spread throughout the site.

**Comment by Apexal** [comment]
When printing any page, there should be a surprise...
`<link media="print" href="print.css" />`

**Comment by Apexal** [comment]
I will also leave this for RCOS members come September!

**Comment by cbnt7437** [comment]
"Priority: High"
Agreed. Nothing is more important than the SIS man...

**Comment by cbnt7437** [comment]
"Priority: High"
Agreed. Nothing is more important than the SIS man...

**Comment by Apexal** [comment]
let's include this somewhere
![image](https://user-images.githubusercontent.com/8422699/65907688-d03e8780-e392-11e9-97b0-7c901bee2ca1.png)
