### ISSUE TITLE
Study Groups

### ISSUE THREAD

**Issue by reersa** [Apexal/late#369]
I feel that it could be very helpful for people to create Study Groups as a private or public event. Private study groups would be able to be shared with specific user and public study groups would be tied to the specific class. The study group could either be just a date time location kind of thing or it could be some interactive platform. This would allow students to connect and to study together and connect as a community.

**Comment by Apexal** [comment]
This would be a great addition to #343 which currently allows students to share assignments with other users. 

Study Groups can be similar to work blocks but not attached to specific assignments or exams like work blocks are.

I'm even imagining a directory for all logged in students where they can find public study groups that are looking for members. This would be the start of adding social features.

Is that similar to what you envisioned?

**Comment by reersa** [comment]
Yes I think that would be perfect

**Comment by Apexal** [comment]
Out of LATE's scope.
