### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by nishi7409** [Apexal/late#378]
**Describe the bug**
Tries to add class schedule to Google Calendar, runs into an error

**To Reproduce** *optional*
https://streamable.com/46s66

**Expected behavior**
https://streamable.com/46s66

**Screenshots** *optional*
https://streamable.com/46s66

**Device**
Windows PC

**Comment by Apexal** [comment]
Good catch. This button only works after you have connected your Google Account on the Notifications Setup page: https://www.late.work/account/integrations#google-calendar

I will have that button redirect to that page if the student has not yet done this.
