### ISSUE TITLE
Calendar Blocks

### ISSUE THREAD

**Issue by nishi7409** [Apexal/late#380]
**Describe the bug**
Calendar blocks are too small to be viewed. 

**To Reproduce** *optional*
Login and view the calendar on your phone

**Expected behavior**
![484A1D3F-0C59-4FB3-BD2D-AC1C37FF3397](https://user-images.githubusercontent.com/20250366/63429419-f7935380-c3e7-11e9-8bac-8b7e8cf204b3.png)

**Screenshots** *optional*
![484A1D3F-0C59-4FB3-BD2D-AC1C37FF3397](https://user-images.githubusercontent.com/20250366/63429419-f7935380-c3e7-11e9-8bac-8b7e8cf204b3.png)

**Device**
iPhone XR

**Comment by Apexal** [comment]
I will have the calendar display 3-days instead of 5-days when on mobile.
