### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by nishi7409** [Apexal/late#382]
**Describe the bug**
Logging out of the website doesn’t send you back to the home page.

**To Reproduce** *optional*
https://streamable.com/1vvfh
Simply log out.

**Expected behavior**
https://streamable.com/1vvfh

**Screenshots** *optional*
https://streamable.com/1vvfh

**Device**
iPhone XR (but it’s not device specific, just change the href)

**Comment by Apexal** [comment]
Seems to not be possible thanks to how RPI's CAS server works.
