### ISSUE TITLE
Promo videos don't work on Safari

### ISSUE THREAD

**Issue by nishi7409** [Apexal/late#384]
**Describe the bug**
Videos that are shown on a PC (from the home page) aren’t present on mobile.

**To Reproduce** *optional*
https://streamable.com/52eky

**Expected behavior**
https://streamable.com/52eky

**Screenshots** *optional*
https://streamable.com/52eky

**Device**
iPhone XR

**Comment by Apexal** [comment]
This could be an issue with Safari not supporting the format of the videos... I'll research this

**Comment by nishi7409** [comment]
Actually, this was on Google Chrome, the app on my iPhone.

**Comment by Apexal** [comment]
Ah, I was referring to the fact that iOS does not support or allow third party browser render engines so although it is the Chrome app, it's the same under the hood as Safari.

This is assuming that this issue pertains to that browser rendering engine of course.

Could you check to see if this happens on Safari as well?

**Comment by zacharylove** [comment]
I've noticed this issue persists even after the recent promo page changes. According to Apple's documentation:

> Safari on iOS (including iPad) currently supports MPEG-4 video (Baseline profile) and QuickTime movies encoded with H.264 video (Baseline profile) and one of the supported audio types.

I'll add an MP4/H.264 video fallback for the promo videos and see if anything changes.

**Comment by Apexal** [comment]
Returning to this now.

**Comment by Apexal** [comment]
This still happens. I am using ffmpeg to create mp4s
