### ISSUE TITLE
Discord integration fails

### ISSUE THREAD

**Issue by dmandras** [Apexal/late#385]
**Describe the bug**
When trying to integrate discord, after logging in, it will either bring you to your server list or come up with an error message, shown in the second screenshot below. 

**To Reproduce**
1. Go to "Edit Account"
2. Notifications
3. Under integrations, select discord and log in to link it.

**Expected behavior**
Integrates Discord with LATE

**Screenshots**
https://snipboard.io/2v9yqw.jpg
https://snipboard.io/L2OJl5.jpg

**Device**
Win10 x64, Latest stable Chrome

**Comment by dmandras** [comment]
Video link, just in case:
https://streamable.com/2dxlf

**Comment by Apexal** [comment]
Found the issue. The old url of the website used to be `rpi-late.herokuapp.com` and the Discord authentication still uses that url instead of `late.work`. Fixing now.
