### ISSUE TITLE
Saving Past Todos

### ISSUE THREAD

**Issue by morningcatt** [Apexal/late#386]
Currently, Todos disappear when you clear them. Could we please have the past todos save, perhaps onto a lower panel in that tab to see what has been completed?

**Comment by robere2** [comment]
Task list for now:

- [x] Ability to view previously completed items
- [x] Ability to un-check completed items
- [x] Ability to edit the names of todo list items
- [x] Archive to-do list items that have been checked off for a certain amount of time (make all still downloadable?)
