### ISSUE TITLE
claimed my major was undeclared

### ISSUE THREAD

**Issue by brendanrufo** [Apexal/late#389]
I used the import from SIS function to import my information, and it claims to have successfully retrieved my major from SIS, when it has given me undeclared. I am a GSAS major, so I'm fairly certain this is inaccurate. SIS accurately displays my major so I don't think this is an issue due to me being a freshman.
[Describe the problem that occurred as best as you can here]

I am unsure how to reproduce this error as i have only importanted once with one set of information

**Expected behavior**
I had expected to be given the GSAS major

**Device**
Windows PC using Chrome

**Comment by robere2** [comment]
This should be fixed once #410 is complete.
