### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#39]
Implement a way to show flash messages. These are the messages the status updates that appear after actions like 'Saved new assignment' or 'Failed to create assignment'

There must be a Koa package for this but if there isn't it's easy enough to implement.

**Comment by kvverti** [comment]
I think the standard way to do this is with AJAX? The default `<button type="submit"/>` doesn't really give much room for customization.

**Comment by Apexal** [comment]
The way I've typically seen is keeping a `flash` object in the session which is passed to the views by `ctx.state.flash` and is reset at the end of each session. This removes the need for AJAX.

**Comment by Apexal** [comment]
https://github.com/Apexal/examen/commit/69f9a861e4392fd321d973adea1d2a2b3d05f242

**Comment by kvverti** [comment]
Do we have a test case for the flashes?
