### ISSUE TITLE
Dorm Directory

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#390]
Until the maintainers of RPI Rooms get back to me, I am going full steam ahead on this.
---
Basically recreate RPI Rooms but have students upload photos on the spot or take them from their phone directly. Have admins confirm submissions before making them public. The tool should be public and respect the privacy of submitters. It will not say the room number or the person who submitted.

When viewing, the DATE TAKEN will be clearly visible and the directory should be categorized by dorm and grade level as well as room type.

**Comment by Apexal** [comment]
https://www.npmjs.com/package/sharp

**Comment by Apexal** [comment]
All that is left is:
- [x] compress and resize images
- [x] add the rest of the dorm data
- [ ] add address of each dorm with link
- [ ] flesh out view dorm page, with pagination for each style
- [ ] implement sorting on home and view
- [ ] Advertise advertise advertise!

**Comment by Apexal** [comment]
For the dorm photo directory, students should be able to submit photos of the dorm from the outside, if they happen to have. They should also be able to submit photos of different areas of the dorm and these should be separated from the room photos.

**Comment by Apexal** [comment]
I am leaving the rest of this to my RCOS team.

**Comment by robere2** [comment]
Backend todo list:

- [x] Add dorm list model to database
~~- [ ] Add scraping for the list of dorms~~ Will be added by admins manually
- [x] Add scraping for dorm attributes
- [x] Add API to fetch dorm data
- [x] Add user interaction system for dorms
  - [x] Reviews (unlimited)
  - [x] Ratings (limited times per year on dorms, unlimited for reviews/questions/answers)
  - [x] Questions (unlimited)
  - [x] Redact author data on anonymous submissions
  - [x] Add aggregation to dorm questions and answers (See 02fad0a6 and 3a17fcc7)
  - [x] `populate()` any remaining data (e.g. dorms, authors, etc)
- [x] Revitalize photos system
  - [x] Allow photos of common areas
  - [x] Allow for descriptions
- [x] Add general questions section. Should use same system for dorm-specific questions.
- [x] Investigate potential ReDoS vulnerability in current searching implementation.
- [x] Add pagination to questions and reviews systems
- [x] Assert users are logged in before attempting actions that require it.

https://sll.rpi.edu/housing-comparison

**Comment by robere2** [comment]
I think it could be interesting to have ratings and/or (approved?) comments so students weighing their choices can get the thoughts of others. On the other hand, many of the pros/cons are already listed on the dorms pages. Any thoughts?

**Comment by Apexal** [comment]
> I think it could be interesting to have ratings and/or (approved?) comments so students weighing their choices can get the thoughts of others. On the other hand, many of the pros/cons are already listed on the dorms pages. Any thoughts?

I love that idea. Although the stats are listed as you said, the experiences of students give a way better idea for what to expect from dorms.

**Comment by robere2** [comment]
I don't know much about it, however Github Education just received a new partnership with [Scrapinghub](https://scrapinghub.com/) . Worth looking into for the backend if this is a more reliable service for scraping dorm data than something homemade, and if it does what we want it to. Could also be overkill.

**Comment by Apexal** [comment]
That's so funny. I was literally reading the email about that and thinking similarly as I received the email about your comment! Definitely something to check out.

**Comment by cvitus** [comment]
Frontend Brainstorming:
- update dorm cover photos with default image 
- on hover over dorm room, slideshow through all images uploaded
- add junior, senior housing
- implement review/comment feature with thumbs up/down
- possibly include the floor plans
- include travel time to main part of campus / location on map
- maybe a little quick info section to include general info

**Comment by robere2** [comment]
As stated, backend is done. Here's a list of things it supports, as well as documentation/examples using Postman. Long message as I wanna cover everything I changed.

- **Basic Dorms API**
  - Dorms can be fetched automatically using scraping, or inserted manually
    - Automatic dorms take 1 `key`, which is the dorm's key found on the SLL website URL (e.g. [Hall Hall's](https://sll.rpi.edu/buildings/hall-hall) key is `hall-hall`)
    - If a `key` is absent, the dorm is assumed to be manually filled. 
    - Keys must be between 3 and 100 characters. Check the `dorms.model.js` file for other limits.
  - Automatically fetched dorms can be refreshed by sending GET request to `GET /dorms/refresh`
  - A script can be set up on the backend to automatically refresh the data every day or so (@Apexal).
  - Only Admins can create dorms
- **Dorms Reviews API**
  - Users can post a review about any dorm
  - Reviews can be up to 2000 characters. Titles must be less than 40 characters.
  - Reviews can be anonymous
  - Users can edit or delete their own reviews, admins can edit any.
  - Pagination is supported. I am imagining an [infinite scroll style page](https://scrollmagic.io/examples/advanced/infinite_scrolling.html), but up to you
  - Searching is supported
- **Dorm Questions API**
  - Users can post a question about any dorm, or no dorm at all (general questions).
    - If no dorm ID is provided when fetching the list of questions, the API returns general questions.
  - Questions can be anonymous. Users can edit and delete their own questions, admins can edit/delete any.
  - Pagination is supported. I am imagining an [infinite scroll style page](https://scrollmagic.io/examples/advanced/infinite_scrolling.html), but up to you
  - Question titles can be up to 2000 characters however this should probably be changed.
  - Searching is supported
  - **Question Answers API**
    - Users can answer any question. The answer CANNOT be anonymous.
    - Users can edit and delete their own answers, admins can edit and delete any.
    - Answers can be up to 2000 characters.
- **Dorm Photos API**
  - Each photo can have a description and can be anonymous.
    - Descriptions can be up to 200 characters long.
  - Users can post photos of any dorm.
    - Photos must be confirmed by an admin after posting
  - Users can get a list of all photos that are confirmed, AND their own unconfirmed photos. Admins will receive a list of all photos, regardless of confirmed or not.
  - Users can edit or delete their own questions (regardless of confirmed status), but admins can edit and delete any photo.
    - Only admins can edit the `confirmed` status of photos.
- **Voting API**
  - A general voting API exists for all of the above. Users can vote either positively or negatively for dorms, photos, questions, reviews, and question answers.
  - Votes are anonymous.
  - Users can also remove their vote.
  - A cumulative "rating" score is returned with all of the above when you `GET` them.
  - Users can give an infinite number of ratings, however they're limited to rating 2 dorms per 90 days. Removing a rating will give you the ability to rate another one.

One thing to note, the difference between what POST and PUT do here: Posting _new_ content is generally via a `POST` request, while editing old content is done via a `PUT` request.
Docs/examples on Postman. Not sure how much you know about HTTP requests and such so if you don't know how to use Postman or much about how to use the backend in general, I can show you at next RCOS meeting if you'd like. You can test the HTTP requests yourself, or you can view sample requests and responses under the "Examples" dropdown in the top right of each request.
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/e82bc01844e16efd45df)

Some things which perhaps should be added to the backend based off of what you mentioned:
- Mailing Address/Actual Address
- Floor Plans
- "General info" section that can be manually filled by admins
Most likely these would all have to be filled manually. The [floor plans links here](http://zim2411.info/floorplans/) don't seem to follow any specific format.
NOTE: All paginated data is sorted by newest to oldest. It might also be ideal to also have a way to sort by highest rated to lowest rated.

If there's anything else that anyone thinks should be added or if you have any questions let me know, or you can add them yourself. Also if there's anything here that _isn't_ used then we can remove it.

**Comment by robere2** [comment]
Oh, also, users can be banned from posting or editing content. I've added this to the `Student` model. Banning or unbanning a user is as simple as executing a normal edit user request, I believe. Users can only be banned temporarily (until a Date), however can be made effectively permanent by increasing the date until at least a few years past their graduation. An example of a banned user response is in the examples for `PUT /dorms/photos/:photoID`. A way to ban/unban could probably be added to the student list, as well as on the individual items they post.

This also makes me realize that there's currently no way for admins to ban users who post anonymously. Perhaps post authors should not be hidden for admins?

**Comment by Apexal** [comment]
Out of LATE's scope.
