### ISSUE TITLE
Edit Assignment Switching Assignments

### ISSUE THREAD

**Issue by reersa** [Apexal/late#401]
When you are editing an assignment after having created it, you have the option to click the pencil icon next to the name and the due date for example. When you go to edit these fields, everything works as expected, however, if you change a field without saving and then select a different assignment to edit, the most recent edits stay visible for the newly selected assignment. There should be an event attached to clicking on a new assignment that if there are changes made to the assignment it should prompt the user to save those changes before switching assignments.

**Comment by Apexal** [comment]
do this, 4head @reersa 

1. `$ git checkout -b fix-issue-401` (make new branch for this)
2. fix this in the files
4. `$ git add --all`
5. `$ git commit -m "Fixed edit assignment switching bug"`
6. `$ git push origin fix-issue-401`
