### ISSUE TITLE
Assessment Reminders

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#406]
Last night I did my EProb homework. I finished the whole thing, and decided to scan the document and hand it in tomorrow, since it was so late.
Needless to say, I didn't remember to hand it in, after all my hard work. Sure, I could just take this as a lesson to hand things in as soon as I'm done. But LATE is made for those who are bad at this type of thing, like me. 
Therefore, LATE should send a text to the user to remind them an assignment is due on LMS/Gradescope 30 minutes beforehand. Because 4pm is such a weird time to remember.

**Comment by Apexal** [comment]
I'm going to start a branch for this!
