### ISSUE TITLE
Student WhenIsGood

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#412]
[WhenIsGood](http://whenisgood.net) is great but extremely clunky and awkward to use! I have seen first hand that its difficult for students to meet up to study or work together due to schedule differences.

If LATE knows both your course schedule and your unavailability... it knows when is good for you!

We can have students find the best times to meet with others by simply adding their names.

e.g. `matraf` and `tedess4` want to meet up, one of them can simply throw in the other's rcs id and be told *and shown* what times work for both of them. This can be scaled to any number of students.

### Privacy
Obviously a student won't be able to just throw in a random rcs id and see the target's schedule. Students will be able to opt-out entirely of this on their profile page, and it will never show *where* a student is or what courses they are in. It will only show "In Class" or "Unavailable" and match those up.

What does everyone think?

**Comment by robere2** [comment]
I think this is a good idea however at the moment LATE doesn't know _your entire schedule_. There would be a number of times where LATE would say "okay!" when you're out of town, or have a club event, etc.

A way for clubs to post their own schedule for club members could be an interesting idea moving forward.

**Comment by cbnt7437** [comment]
I think this should be implemented after we enhance the “other” category to include club meetings, meal times, etc. That way, LATE would really have your complete schedule, as opposed to just having your classes and your study schedule.

**Comment by arachiele** [comment]
Would it possible to pull all available/unavailable times from Google Calendar? Instead of seeing available/unavailable times of others, it might be better if you can only view available times that correspond to _both parties_, and then both users can select or "suggest" a preferred time based on these possibilities.

**Comment by Apexal** [comment]
> Would it possible to pull all available/unavailable times from Google Calendar? Instead of seeing available/unavailable times of others, it might be better if you can only view available times that correspond to _both parties_, and then both users can select or "suggest" a preferred time based on these possibilities.

Turns out Google Calendar's API makes that [really really easy](https://developers.google.com/calendar/v3/reference/freebusy/query) to the point where it can directly tell us the free blocks of time a user has in between a given start and end.

**Comment by Apexal** [comment]
This now exists as a simple Vue static SPA https://github.com/Apexal/free I can easily port it to LATE and integrate it.

**Comment by Apexal** [comment]
Out of LATE's scope.
