### ISSUE TITLE
GCal does not automatically populate

### ISSUE THREAD

**Issue by nprisament** [Apexal/late#414]
**Describe the bug**
[Describe the problem that occurred as best as you can here]

**To Reproduce** *optional*
*Example:*

**Expected behavior**
[Write what you expected to happen here.]

**Screenshots** *optional*
If applicable, add screenshots to help explain your problem. I recommend using https://snag.gy/

**Device**
[Put info about the device you were on when you found the bug, e.g. iPhone X, Windows PC, etc.]

**Comment by Apexal** [comment]
Depends on #397
