### ISSUE TITLE
Make academic calendar events separate from the regular calendar

### ISSUE THREAD

**Issue by martin-stefan** [Apexal/late#426]
academic calendar events take up too much space on the personal calendar and forces personal events out of the way

**Describe the solution you'd like**
I would like to move academic calendar events to a different spot, or just a better way to put them in

**Comment by Apexal** [comment]
Time to knock this out already!

**Comment by Apexal** [comment]
RPI totally broke their own calendar exporting system... :man_facepalming: 

https://events.rpi.edu/cal/calendar/showCalendarForExport.rdo

**Comment by Apexal** [comment]
These are still broken. I should bring this to the IT department's attention...
