### ISSUE TITLE
LATE Battle Royale Game

### ISSUE THREAD

**Issue by aidan-lane** [Apexal/late#435]
Start a custom BR game with people online.

Suggestions?

**Comment by marinater** [comment]
Implement the ski hill, java beans, pizza tron and fishing game Club Penguin?

**Comment by tobiasjpark** [comment]
As mentioned in today's meeting, maybe tie this in with the proposed points system - if people have good time management, reward them with points that they can use to play game?

**Comment by Apexal** [comment]
One day...
