### ISSUE TITLE
Unavailable Time Block Creation Shows Incorrect End Time

### ISSUE THREAD

**Issue by Shadowsoftime99** [Apexal/late#436]
**Describe the bug**
When trying to create an Unavailable Block, the pop-up window that prompts for a name shows the end-time as equal to the start time, always.

**To Reproduce** *optional*
1. Go to the "Unavailability" tab of the Account setup screen
2. Attempt to create an unavailable block.
3. Note the pop-up; it should display an incorrect end-time

**Expected behavior**
The end-time should be the bottom of the block

**Screenshots** *optional*
![LATE bug](https://user-images.githubusercontent.com/16748195/65549196-0db29900-deeb-11e9-8682-ee835861701b.png)

(you can see the currently-unnamed block on the right; it should be from 6pm to 11pm)

**Device**
Windows 10 PC; but this bug is universal

**Comment by Apexal** [comment]
Does this happen with any user? What rcs id do you use when testing this?

**Comment by Shadowsoftime99** [comment]
It happens with at least my and your RCS IDs; it should just be always.
