### ISSUE TITLE
Update the Wiki to include outline for new developers

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#439]
Frank: add something like this to wiki
All developers who want a refresher or are new to JS: read on. Many great resources were mentioned as the last meeting, but it can be a little overwhelming because those resources will teach you _everything_, including things you don't necessarily need to know for LATE. Of course, you should take advantage of them all! But if you're like me, you are impatient and want to start really working and learn all of those other little things as you go. So, what do you need to know _right_ now, so you can start coding for LATE as soon as possible? 
Start by going to [learn.freecodecamp.com](url). The following is an outline in order of relative importance according to our Lord and Savior, Frank Matranga, of the most vital sections to visit on this website. 
**Responsive Web Design Certification**
     - Basic HTML and HTML5
     - Basic CSS
     - Responsive Web Design Principle
     - CSS Flexbox*
     - CSS Grid*
                   * these two were described as "not necessary, but cool and good for jobs"
**Javascript Algorithms And Data Structures**
     - Basic Javascript
     - ES6
     - Debugging
     - Functional Programming
**Front End Libraries**
     - SASS
**Apis And Microservices** _if you want to start working on backend, learn this_
     - MongoDB and Mongoose
     - Basic Node and Express

**Comment by Apexal** [comment]
Over our next break I'll develop guides on learning HTML, CSS, JS, and Vue for everyone working on LATE. It'll take forever but it'd be ideal to have resources specifically for us.

**Comment by Apexal** [comment]
I created this page as start of the Wiki revamp!
