### ISSUE TITLE
Study Space Directory

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#442]
From the Google Form:
>Shows what study spaces are open or tells you where a god[sic] place to study depending on how you like studying (very quiet, noisy, semi-talkative)

(Unfortunately the user put their RIN instead of their RCS ID so I cannot credit them with the idea.)

LATE can provide a crowd-sourced directory of "study spots" where students can discover a favorite study spot and add it to the directory with some labels so that they can be searched and filtered easily, e.g. Noise Level, Distance, Grade Level Access, etc.

**Comment by robere2** [comment]
It could be worth considering talking with the FLOM guys about this, as there's potential to integrate both of these apps together (a "grand plan" idea maybe). Depends on their progress and their plan.

Alternatively we could simply link to their website for FLOM-supported rooms.

**Comment by Apexal** [comment]
Out of LATE's scope.
