### ISSUE TITLE
User Polls

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#448]
There should be a poll system where admins can create polls primarily to get user feedback. In the future we could open it up for fun.

**Comment by aidan-lane** [comment]
Found this: https://github.com/ppietris/vue-poll, it's under the MIT license.

**Comment by Apexal** [comment]
Awesome. I will find someone to take on this issue tomorrow. It looks like it could be pretty straightforward.

**Comment by Apexal** [comment]
We will now use Polls to get opinions on new features.
