### ISSUE TITLE
Redesign calendar events

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#452]
The current calendar events are too verbose and are somewhat ugly. Unfortunately I am not a graphic designer. Fortunately, I can at least use `position: absolute`. What do we think of this at the very least?

Current:
![image](https://user-images.githubusercontent.com/8422699/65985989-f296da80-e450-11e9-85cc-606ad29e737d.png)

Desired:
![image](https://user-images.githubusercontent.com/8422699/65985948-e3b02800-e450-11e9-8aa4-598b3dc25313.png)

**Comment by Apexal** [comment]
Your work is going to be done in `/src/mixins/fullcalendar.js` which is kinda confusing. Next session I will work with you to show you how to do this @martin-stefan

**Comment by martin-stefan** [comment]
When would be best for you to meet up.

**Comment by Apexal** [comment]
Right now.
