### ISSUE TITLE
Easter Egg: Rick Rolling

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#456]
I would like there to be an Easter Egg that somehow involves sending a link of Rick Astley's hit single "Never Gonna Give You Up" to the user. I don't know how I want to do this, and I would be open to every idea.

**Comment by Apexal** [comment]
Elaborate

**Comment by tobiasjpark** [comment]
How about if you click the logo of SISman on the homepage 7 times then it plays?

**Comment by Apexal** [comment]
Great idea, somebody claim this quick!

**Comment by Apexal** [comment]
Actually I will add this feature tomorrow during small group so everyone can see the full process of adding a new feature to LATE!
