### ISSUE TITLE
Study Timer is cut off when LATE is in half-screen mode

### ISSUE THREAD

**Issue by tobiasjpark** [Apexal/late#477]
**Describe the bug**
When LATE is set to take up half of the screen, this happens:

![Untitled](https://user-images.githubusercontent.com/29665790/66343638-11e2ab80-e91a-11e9-9a5a-a2d65ecf44b2.png)

**To Reproduce** *optional*
1. Open LATE on a 1920x1080 display and resize it take up the right side of the screen only.
2. Open study timer.

**Expected behavior**
Study timer should display normally.

**Device**
Laptop running Windows 10 version 1803. 1920x1080 single display using the LATE Chrome extension/PWA.

**Comment by zacharylove** [comment]
Interestingly enough, I'm having trouble reproducing this bug on my own display, but I will update the timer styling to support squished screens
