### ISSUE TITLE
Study timer notifications only work when window is focused

### ISSUE THREAD

**Issue by tobiasjpark** [Apexal/late#478]
**Describe the bug**
The study timer pushes a little notification to the browser whenever the timer ends; it says something like "Now take a 5 minute break" or "Now work for 25 minutes." However, the notification only shows up when you click on the browser window. For example, when the 25:00 timer runs out, the timer automatically switches to a 5 minute break, but I get no notification and thus keep working. When I realize that the timer has switched to "short break" and is on 2:00 remaining, I click on the LATE window and then get the notification about the break. I believe there may have also been one time when the study timer went from 25:00 work, to 5:00 break, back to 25:00 work, and then I clicked on the window and got the 5:00 break notification.

**To Reproduce** *optional*
1. Open study timer and start it
2. Click your mouse on another window and do not click on the LATE window or bring it into focus.
3. Wait for the timer to switch to short break.
4. Wait a while, then click on the LATE window.

**Expected behavior**
Study timer should somehow still notify you even if it is not the focused window.

**Device**
Windows PC, LATE Chrome extension.

**Comment by Apexal** [comment]
Great catch. We can look into how to make the end of a period more obvious and how to hold off from starting the next period until the user has acknowledged the end of the current one.

**Comment by tobiasjpark** [comment]
Yeah, I noticed we also have a little beep when the timer goes off but it's kind of quiet.

**Comment by Apexal** [comment]
This could also be something to work on next! @kd2eom

**Comment by tobiasjpark** [comment]
Possible solution would be to do the following:

- [x] Display remaining time dynamically in the webpage's title so users can see time remaining even when LATE is in an inactive tab
- [x] Use Buefy dialog instead of JS alert
- [x] Make the timer notification sound continue until the user excuses the notification box
- [x] Do not resume timer until notification box is excused
- [x] Send push notifications to desktop when timer goes off using techniques from #224

**Comment by Apexal** [comment]
Awesome ideas!
Check out #224 for more info on Push Notifications

**Comment by Apexal** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

**Comment by tobiasjpark** [comment]
Also going to change the alert box to use a Buefy dialog
https://buefy.org/documentation/dialog/

This will also help us allow the timer sound to play while the notification box is displayed, and have the sound stop when the box is dismissed.
