### ISSUE TITLE
Simpler Animations for Tools Page?

### ISSUE THREAD

**Issue by tobiasjpark** [Apexal/late#487]
This is just my opinion, but I feel like the animation on the Tools page might be a bit too much; if you move your mouse over several items quickly in order to get your cursor over to the item you want, you are met with 3 very big animations all running almost at once, which can be a bit overwhelming and distracting. Perhaps we could tone it down a bit and use a simpler animation here? 

Thoughts?

![animation](https://user-images.githubusercontent.com/29665790/66448021-227c4a00-ea1e-11e9-86f9-fe85e8d1e86c.gif)

**Comment by tobiasjpark** [comment]
The Account Setup page seems to still use the old animations (when the tools are displayed after setup is complete - see screenshot).

Not a big deal, but do we want to change this as well to make things consistent?
![screenshot](https://user-images.githubusercontent.com/29665790/68249850-a01b8180-ffed-11e9-9994-8bea24505efd.png)

**Comment by Apexal** [comment]
Changing it would be best.

**Comment by zacharylove** [comment]
![accountComplete](https://user-images.githubusercontent.com/12072877/69285541-24a9fa80-0bbf-11ea-849e-4badef578e19.gif)
Account Complete buttons mirror the Tool Index buttons
