### ISSUE TITLE
Warn about adding duplicate assessments

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#492]
Once or twice I've forgotten that I added an assignment or exam to LATE a while back and accidentally added it again. LATE should warn (but still allow) users if they try to add an assessment and there is an upcoming assessment in the same course with the same title, e.g. `Homework 3`

**Comment by Apexal** [comment]
I will drop info about this here as soon as I get the chance!

**Comment by Apexal** [comment]
For this issue you will be working with the upcoming assessments (assignments and exams) that Vue keeps track of once it has requested them at the first page load. These can be easily accessed with `this.$store.state.assessments.upcomingAssessments`! Its an array of assignments and exams. You can search loop through it with a classic imperative for loop *or* the cool functional way.

For example, if you wanted to find a single assessment with a particular ID of `searchID`:
```js
this.$store.state.assessments.upcomingAssessments.find(assessment => assessment._id === searchID)
```

Heres a good (but long) resource on functional programming that you can read to get a taste of it: https://itnext.io/the-power-of-functional-programming-in-javascript-cc9797a42b60

@silenciador9

**Comment by silenciador9** [comment]
I will look through all of this asap

**Comment by Apexal** [comment]
You will need something like this:
```js
// Check if this sort of assignment exists already
if (this.$store.state.assessments.upcomingAssessments.find(assessment => assessment.title === title && assessment.courseCRN === courseCRN && assessment.dueDate == dueDate)) {
	alert('You've already added this assignment!')
}
