### ISSUE TITLE
Buefy icons not appearing in some cases

### ISSUE THREAD

**Issue by aidan-lane** [Apexal/late#493]
**Describe the bug**
Using buefy icons with buttons / inputs, results in a blank space.

**Expected behavior**
Expect icon to appear in button

code:
`<b-button
        type="is-danger"
        icon-right="delete"
        @click="deleteAllPolls"
      >`

**Comment by Apexal** [comment]
Would you consider this closed?

**Comment by aidan-lane** [comment]
yup!
