### ISSUE TITLE
Explore hosting ideas

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#50]
Possibilities:
- Heroku
- Google Cloud Platform
- DigitalOcean
- AWS
- Azure

I recommend: **Heroku** for its ease of use and free tier.

**Comment by IncognitoCactus** [comment]
Something of note is that Google Cloud Platform offers a student program with free hosting for projects such as these, and that RPI's in that program: https://cloud.google.com/edu/.
Heroku is limited to 1000 dyno hours/month, although they suspend applications after 30 minutes of inactivity.
I believe the other options only offer discounts to students, not free hosting.

**Comment by Apexal** [comment]
While Zach's above comment about Google Cloud seems promising for real hosting when we are ready, I've currently setup Heroku to hold the dev server for general testing.

https://rpi-late.herokuapp.com/
