### ISSUE TITLE
"Other" Course

### ISSUE THREAD

**Issue by Erastos** [Apexal/late#500]
**Describe the bug**
I have a course called Other, which displays in the sidebar, but not when I go to edit courses, making it impossible to remove. I not exactly sure how this occurred, other than I imported from SIS when I first created my account and it was there. 

I expected that I should have been able to delete the course from the edit course page

**Comment by cbnt7437** [comment]
Hi Erastos,
My name is Cait, I'm a developer for LATE. 
Our "Other" course is purposefully there. It's supposed to be used for things that need to be done that aren't tied to a specific class. For instance, I have an assignment to edit my 4 year plan, and it's due the day of my advisor meeting. 
Knowing that, would you still like the option to delete that class? Let us know what you're thinking, we love the feedback.

Edit: Sorry andrew, you're a dev. I h8 u

**Comment by Apexal** [comment]
I will make it clearer how the Other course works but for now the functionality will stay the same
