### ISSUE TITLE
Setup Complete Page Buttons do not scale properly

### ISSUE THREAD

**Issue by Erastos** [Apexal/late#502]
**Describe the bug**
[Describe the problem that occurred as best as you can here]

The buttons to go to other parts of LATE do not scale correctly. There vertical width is too short.

**Expected behavior**
[Write what you expected to happen here.]
I expect that the buttons on the page to have a large enough vertical width

**Screenshots** *optional*
If applicable, add screenshots to help explain your problem. I recommend using https://snag.gy/

![gscreenshot_2019-10-15-165251](https://user-images.githubusercontent.com/22089093/66869030-7b8f3500-ef6c-11e9-9402-2a9979edce26.png)

**Device**
[Put info about the device you were on when you found the bug, e.g. iPhone X, Windows PC, etc.]

Linux - Firefox

**Comment by Apexal** [comment]
Seems to be a Firefox issue.
