### ISSUE TITLE
Calendar sometimes duplicates work blocks

### ISSUE THREAD

**Issue by bertrk** [Apexal/late#503]
When manually adding a work block on the calendar, it sometimes displays two matching blocks after requesting one to be added (ex. two "Homework 3" blocks for the same class within the same time period). It doesn't go away- it has to be manually deleted.

To duplicate:
1. Add work block to calendar.
2. See if duplicate assignment appears.

Device: Windows PC using Google Chrome

**Comment by Apexal** [comment]
Yikes! I'll look into what could cause this.

**Comment by SamiFawcett** [comment]
This isn't just for work blocks, this is also for todo blocks. 

I added a to do block, not only did it duplicate, the duplicate couldn't be deleted!!!!

**Comment by SamiFawcett** [comment]
Update: This issue is most likely a visual bug, because refreshed page gets rid of work block AND block cannot be deleted.

**Comment by Apexal** [comment]
I have not been able to reproduce this. Let me know if it happens again!
