### ISSUE TITLE
Further abstract "controller" and "view" in the API for portability

### ISSUE THREAD

**Issue by robere2** [Apexal/late#506]
At the moment, LATE's backend API uses [model-view-controller](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) design principles, with `document/document.model.js` containing the database schema, `document/document.controller.js` containing the methods which take in a Koa context and send out a response, and `document/index.js` which simply links the controller to the Koa router. This does not allow for extensive portability with our data types, as the controllers **must** take in a Koa context, and **must** send out an HTTP response. 

As an example, consider the following:

**foo/foo.controller.js**
```js
const Foo = require('./foo.model')

async function createFoo(ctx) {
    const f = new Foo()
    f.data = ctx.request.body.data
    f.save()
    ctx.created({ f })
}

module.exports = {createFoo}
```
**foo/index.js**
```js
const KoaRouter = require('koa-router')
const router = new KoaRouter()
const Ctrl = require('./foo.controller')

router.post('/', Ctrl.createFoo)

module.exports = router.routes()
```
If we want to create another object type `Bar` that creates a Foo, we cannot do it without rewriting another Foo creator or throwing an error!
**bar/bar.controller.js**
```js
const FooController = require('../foo/foo.controller')
const Bar = require('./bar.model')

async function createBar(ctx) {
    const b = new Bar()
    b.foo = FooController.createFoo(ctx)
    b.otherData = ctx.request.body.otherData
    b.save()
    ctx.created({ b }) // Throws error because HTTP headers already sent to client in FooController.createFoo
}

module.exports = { createBar }
```

I think a better design would be for our controllers to take in a set of args and return the requested value, if applicable. The view (`index.js` file) would then be responsible for extracting arguments from the HTTP request, passing them to the controller, then sending out the HTTP response once the controller is done.

Example:

**foo/foo.controller.js**
```js
const Foo = require('./foo.model')

async createFoo(data) {
    const f = new Foo()
    f.data = data
    f.save()
    return f
}

module.exports = { createFoo }
```
**foo/index.js**
```js
const KoaRouter = require('koa-router')
const router = new KoaRouter()
const Ctrl = require('./foo.controller')

/**
 * createFoo
 */
router.post('/', (ctx) => {
    try {
        const f = await Ctrl.createFoo(ctx.request.body.data)
        ctx.created({ f })
    } catch (e) {
        logger.error(e)
        ctx.internalServerError('Something went wrong!')
    }
})

module.exports = router.routes()
```

This adds more logic to the view (and makes it slightly harder to read), however it makes all of our controllers significantly more portable and removes the need for a Koa context in (most of our) controller methods.

Any thoughts?

**Comment by Apexal** [comment]
Very wise. Too deep into the current way now though.
