### ISSUE TITLE
Create a LATE Reddit

### ISSUE THREAD

**Issue by cbnt7437** [Apexal/late#542]
Create a subreddit (possibly linked to r/RPI) for LATE. This will possibly increase our web traffic, and branch out to a group of people who don't use/know about github to submit issues.

**Comment by Erastos** [comment]
Just made the Subreddit

**Comment by Apexal** [comment]
Wait me too https://www.reddit.com/r/late_app/

@Erastos what did you name yours?

**Comment by Apexal** [comment]
Out of LATE's scope.
