### ISSUE TITLE
Right Now Block Encouragement

### ISSUE THREAD

**Issue by reersa** [Apexal/late#550]
Under the block that shows Right Now, if you have a test or test later that day, it should show an encouraging message or a random message to motivate you!

**Comment by cbnt7437** [comment]
SO CUTE

**Comment by Apexal** [comment]
If anyone wants to start finding nice messages to show please go ahead! We can either create a list of our own or find an API online for them.

**Comment by Erastos** [comment]
I also think a cat picture should be displayed when the quote is clicked.

Cat Picture API: https://thecatapi.com/
