### ISSUE TITLE
Calendar won't allow work blocks that end at same time assignment is due

### ISSUE THREAD

**Issue by bertrk** [Apexal/late#551]
The calendar won't allow the scheduling of work blocks if the time includes the due date/time (ex. Homework due at 2, but the assignments to select from won't show it if you schedule a work block from 1-2.) 

To reproduce:
1. Create assignment.
2. Try to schedule assignment up to due date/time.
It will not be listed as an option.

Windows Google Chrome

**Comment by Apexal** [comment]
I believe this is caused by one little line in the model for Assignments/Exams that tries to remove blocks that are scheduled outside of the proper range of time. We can check it out today!
