### ISSUE TITLE
Add Assessment from Dashboard Calendar Select Modal 

### ISSUE THREAD

**Issue by cvitus** [Apexal/late#553]
When creating a work block from the dashboard calendar, add feature to be able to create a new assignment or exam and work block directly from there

<img width="1279" alt="Screen Shot 2019-11-15 at 5 18 26 PM" src="https://user-images.githubusercontent.com/42855767/68979602-f649ab00-07cb-11ea-9da1-fc4371aa1325.png">

**Comment by cvitus** [comment]
- [x]  add button for assignment
- [x]  add button for exam
- [ ] create work block

**Comment by Apexal** [comment]
You can use this as a guide:
https://github.com/Apexal/late/blob/d84436a39dad575d4aeac9fe04aea3f91aa212c9/src/views/assessments/AssessmentsUpcoming.vue#L39
