### ISSUE TITLE
Today's Agenda Sidebar Tab doesn't show classes after locally cached page refresh

### ISSUE THREAD

**Issue by doublegulptank** [Apexal/late#572]
**Describe the bug**
When the cached page is refreshed, the Today's Agenda tab no longer shows a list of classes.

**To Reproduce**
1. Open LATE.
2. Press ctrl+shift+r to refresh the page and override the locally cached version..
3. Today's Agenda tab should now say that there isn't anything scheduled for the day.

**Expected behavior**
Courses should remain displayed on screen.

**Screenshots**
Before reload:
![image](https://user-images.githubusercontent.com/43162890/72482623-5c52ae80-37cc-11ea-98a3-4c5fd5a43d88.png)
after reload:
![image](https://user-images.githubusercontent.com/43162890/72482715-aa67b200-37cc-11ea-803d-50c0b7c4bf86.png)
after clicking away and coming back to the tab:
![image](https://user-images.githubusercontent.com/43162890/72482720-af2c6600-37cc-11ea-9dad-64f9476ea30e.png)

**Device**
Google Chrome, Dell Precision 5530, Windows 10 Pro, latest update.

**Comment by Apexal** [comment]
This appears to be a big issue with the cache. I will look into this ASAP tomorrow as I am teaching the rest of the night. Very good catch.

**Comment by Apexal** [comment]
This should be fixed!
