### ISSUE TITLE
SPRING 2020 AGENDA

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#574]
TBC
- [x] Determine RCOS team
- [x] Discuss with Severino Center
- [x] Review student survey responses
  - [x] Determine which features to focus on
- [ ] ~~Review server and potentially switch to Express~~
- [x] Review potential CAS fixes
- [ ] Develop aggregations to crowd-source data
- [x] Hide non-Coursework features
- [x] Fix Google Calendar integration
- [x] Finish automatic notifications with SMS and email
- [ ] Create automated reports
...

**Comment by robere2** [comment]
If someone wishes to work on the dorm directory, the backend API is mostly ready. Just the frontend needs to get done:
https://github.com/Apexal/late/issues/390#issuecomment-552129227
Let me know if you need me to clarify anything in it.
