### ISSUE TITLE
Crowd-Source Assessment Data

### ISSUE THREAD

**Issue by Jerome-Carter** [Apexal/late#589]
Late's users typically enter assignments and exams for each course. What if after a certain number or percentage of students enrolled in the same course enter similarly detailed assignments, those assignments are recommended to the rest of the students in the course.

Maybe there could be a page with recommended assignments to add (if they aren't already). This could be like a calendar or a list of some sort.

Example

Homework 1 -- due 01/12 @ 11:59PM [Add to Assignments] [Ignore] [Down vote]
...
...

- If a student adds the assignment, they will be asked to confirm the details before it is added
- If the student ignores the suggested assignment, it should just be removed from their suggested
- After a specified threshold is surpassed, the suggestion would be removed for all students

Another possible crowd-sourced recommendation could be to review sessions for exams.

Thoughts??

**Comment by bertrk** [comment]
We should also be able to crowd-source data on how many assignments/week classes have (or maybe how many hours estimated work?). This could be used with the course scheduler.

**Comment by Jerome-Carter** [comment]
In addition, it would be great to see crowd-sourced course material for those who take the course in the future.

@Apexal had the great idea of making said material accessible after the semester it was uploaded to prevent plagiarism.

This would also call for a review system in which course material's validity, relevancy, and accuracy are judged. This could also be crowd-sourced.

Proposed previous course-work funnel:
- Potential crowd-sourced assessment created by a student in the course (could be a checkbox or something)
- The assessment is recommended to others (active users) in the course (based on suggestion rate)
- After a certain number of students confirms that the assignment is legit, that suggestion rate will increase and the assessment will be recommended to more students
- When a student completes that assessment, they will be asked if they would like to provide LATE with a copy
  - PDF
  - JPG
  - screenshots of LMS quizzes
- Optionally, one could go back and report the grade they received
- In the next semester, there would be a potential list of back-work for assignments with scores
- There could be an upvote system for students to use

**Comment by Apexal** [comment]
Out of LATE's scope.
