### ISSUE TITLE
Directory Scraper Disabled

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#623]
RPI has removed RPI student's emails from the public RPI Directory search! I bet this was an attempt to combat scam emails.

Now we cannot get a student's name from their RCS ID at all :(

**Comment by robere2** [comment]
Apparently this is fixed. When I visit the directory I'm able to get students emails again.

**Comment by Apexal** [comment]
Oh snap, good catch. I'll make sure the current code always attempts this and handles if it ever breaks again.
