### ISSUE TITLE
Utility pluralize function

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#68]
To avoid tiny issues like `1 Periods` on the front-end there should be a simple util function that takes the number, the singular word, and the plural word, e.g. `pluralize(1, 'period', 'periods)` -> `1 period` and `pluralize(5, 'period', 'periods')` -> `5 periods`

Credit to @IncognitoCactus for pointing this out

**Comment by aeksco** [comment]
I use [pluralize](https://github.com/blakeembrey/pluralize) on @codotype and it's very good
