### ISSUE TITLE
Social Interactions

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#69]
This is a long-term idea.

Once the basic functionality of **LATE** is completed, namely the automatic scheduling function, and once we have user data...

We can introduce incentive to stay on work schedule with levels of social interaction. Some possible ideas include:
 - a friend system
 - public profiles with "scores"
 - global statistics

What do you guys think?

**Comment by Apexal** [comment]
> I believe a cumulative scoring system will not lead to prolonged user retention and discourage new user experience with the program, since the scoring system is meant as a method of competition. Since the interactions are meant to be developed once a large user base is established, we should focus on comparing the user performance to the average value. For instance, if a user completes DS homework #6 in 5 hours with 20 test cases passed, we can encourage the user that he/she is at the 70 percentile in terms of total time used and 50 percentile in terms of score.
@wangbowen1401 

Why do you think a scoring system is discouraging for new users?

I definitely agree with your idea on average performance comparisons. I'm not sure if we will ever be able to have as detailed comparisons as your example of DS homework just because the logistics differ for each course, but definitely we can work on a sort of categorizing system that can determine the type of assignment inputted by the user (we could of course have the user set this when adding an assignment but we should ideally not bother them more than we have to) so that we can compare all "problem sets" in a course, or "labs" or whatever the category is.

We will discuss this further at the meeting, I'll let you know what comes of it!

**Comment by Deantes99** [comment]
I had an idea about the friend system:
That users would be able to single out times that they blocked out times they have class with other users. Also, set times to work together, and copy study times from other users.

**Comment by Apexal** [comment]
I'm going to start working on this in a little different way. I'll further flesh out the Profile setup page and make those opt-out public.

I'll allow students to display their major and similar info.

**Comment by Apexal** [comment]
Out of LATE's scope.
