### ISSUE TITLE
Allow editing of assignment

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#78]
Im thinking that in Assignment Overview that shows on click of a specific assigment, in addition to removal, allow editing of fields such as title, due date, priority..

**Comment by Apexal** [comment]
do note `feature_spa` just got merged to master, be sure to pull first, I don't recall if AssignmentOverview was edited

**Comment by AbigailMedina** [comment]
Work is being done for this on editAssignment branch

**Comment by Apexal** [comment]
@AbigailMedina 	checkout from `feature_spa` to get the edit assignment API route

The request body is just an object with the schema of the assignment, e.g.

```json
{
	"title": "New Title",
	"timeEstimate": 3.5
}
```

**Comment by Apexal** [comment]
`feature_spa` now has API route for editing
