### ISSUE TITLE
Choose storage system

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#8]
There are a few possible database systems to use (not limited to):
- Google Tasks
- Google Firebase
- Google Calendar
- MongoDB
- Relational database

Each must be discussed with its pros and cons.

**Comment by t80088** [comment]
We'll probably need somewhere to store the data online as well as give the user the ability to do something with their data (i.e putting it on the calendar)

I feel like for data storage we can't go wrong with firebase. It's reliable, and has fairly easy to use API calls (iirc). I've used it a bit before so I'd be happy to look more into it if you want me to. 

As for what do do with user data
Imo we should give the user as many options as possible for where they put their info, but for the LVP I think we need to support ical & Google calendar.

**Comment by Apexal** [comment]
## We will use comments here to discuss and store info on potential options
*Feel free to comment a write up on an option you'd like to use!*

### [Google Tasks](https://developers.google.com/tasks/)
Google Tasks appears to have a pretty good API which would be easily available to use once Google authentication is set up. We wouldn't have to hold any data on our end at all.

*Pros*
- Handled all by Google: we don't have to worry about a database
- Pre-made free API

*Cons*
- No way to store metadata: only info that can be stored is due dates and subtasks
- Exposed to user through Tasks app: user can accidentally change or break data

**Comment by kvverti** [comment]
[Google calendars extended properties](https://developers.google.com/calendar/extended-properties) allow storing private or shared metadata with a calendar event. We could use these to store event related data that aren't in events by default. We could also store hashes/checksums or results from whatever algos we decide to use.

**Comment by Apexal** [comment]
Shweta @burgus7 pointed out a feature on the Google Calendar mobile app "Goals" which appears to schedule things like "Relax" or "Read" automatically throughout your schedule at "good times." This is pretty similar to what we are looking for, so perhaps we can look into how this works and try to emulate it!

**Comment by Apexal** [comment]
Today we discussed in the small group a couple different possibilites but it became clear that before we can settle on specifics we must meet as a large group and figure out the basic UX of the website.

**Comment by Apexal** [comment]
Using mLab we can use MongoDB and have the databases hosted on their free sandbox tier. I provisioned a database and will send the credentials in the Slack.

We cam still look into alternatives like Firebase.

**Comment by Apexal** [comment]
I setup MongoDB in the `mongodb` branch and will make a pull request soon.

Next step is to set everyone up with the proper credentials for the database, and to ensure they don't accidentally get pushed to the repository.
