### ISSUE TITLE
VueJS Best Practices

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#86]
There certainly is messy code throughout some Vue components due to rushed coding and testing. We should use the [VueJS guide](https://vuejs.org/v2/guide/) and review components to ensure they use best practices.

One example I can think of is dynamic styling.

**Comment by CometS1** [comment]
I can try to work on this. Which Vue components are you referring to?

**Comment by Apexal** [comment]
https://vuejs.org/v2/style-guide/
