### ISSUE TITLE
Assignment search

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#98]
There should be a basic search function in the PastAssignments view.

**Comment by Colton-Zecca** [comment]
Beginning Progress

**Comment by Apexal** [comment]
The problem with this is that currently the PastAssignments page let's the user browse week by week. How should search/filter work then? Should it search only the currently displayed week of assignments or search *all* past assignments? The first way can be done on the client without extra API calls but is not very useful, the other requires a new API route to search all past assignments on the back end.
